[package]
name = "rust"
version = "0.1.0"
authors = ["Morten Dahl <morten.dahl@snips.ai>"]

[dependencies]
paillier = { version="0.1" }

[dev-dependencies]
bencher = "0.1"

[[bench]]
name = "runme"
harness = false
